---
title: "RRBS Final dataset (used for DMPs) Data Exploration"
author: "Isabel Castanho (I.S.Castanho@exeter.ac.uk)"
date: "`r Sys.Date()`"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load Data, warning = F, message = F}
library(dplyr)
library(tidyr)
library(qqman)
library(gldrm)
library(ggplot2)
library(ggfortify)
setwd("/gpfs/ts0/projects/Research_Project-191406/isabel/RRBS_new/")

# J20
## Phenotypic data
pheno <- read.csv("/gpfs/ts0/projects/Research_Project-191406/isabel/RRBS_new/J20_coldata_RRBS.csv", row.names=1, stringsAsFactors=FALSE)
pheno$Age_months <- as.numeric(pheno$Age_months)
pheno$Genotype <- as.factor(pheno$Genotype)
pheno$Genotype <- relevel(pheno$Genotype, "WT")
levels(pheno$Genotype)

## Remove samples that have NA for pathology
pheno_ECX <- pheno[,c("Genotype", "Age_months", "Histology_no", "ECX")]
pheno_ECX_clean <- na.omit(pheno_ECX)
pheno_ecx_J20 <- pheno_ECX_clean

## Load methylation data (merged data, BiSeq + coverage filtering)
load(file = "/gpfs/ts0/projects/Research_Project-191406/isabel/RRBS_new/J20_RRBSbetasComplete.RData")
# RRBS_completebetas

# Load methylation data filtered by quantiles
load(file = "/gpfs/ts0/projects/Research_Project-191406/isabel/RRBS_new/J20_quantilesFiltering.RData")
# outliersDat, newDat
betas_ecx_J20 <- newDat[,rownames(pheno_ecx_J20)]
betas_ecx_J20_outliers <- outliersDat


# rTtg4510
## Phenotypic data
pheno <- read.csv("/gpfs/ts0/projects/Research_Project-191406/isabel/RRBS_new/Tg4510_coldata_RRBS.csv", row.names=1, stringsAsFactors=FALSE)
pheno$Age_months <- as.numeric(pheno$Age_months)
pheno$Genotype <- as.factor(pheno$Genotype)
pheno$Genotype <- relevel(pheno$Genotype, "WT")
levels(pheno$Genotype)

## Remove samples that have NA for pathology
pheno_ECX <- pheno[,c("Genotype", "Age_months", "Histology_no", "ECX")]
pheno_ECX_clean <- na.omit(pheno_ECX)
pheno_ecx_Tg4510 <- pheno_ECX_clean

## Load methylation data (merged data, BiSeq + coverage filtering)
load(file = "/gpfs/ts0/projects/Research_Project-191406/isabel/RRBS_new/rTg4510_RRBSbetasComplete.RData")
# RRBS_completebetas

# Load methylation data filtered by quantiles
load(file = "/gpfs/ts0/projects/Research_Project-191406/isabel/RRBS_new/rTg4510_quantilesFiltering.RData")
# outliersDat, newDat
betas_ecx_Tg4510 <- newDat[,rownames(pheno_ecx_Tg4510)]
betas_ecx_Tg4510_outliers <- outliersDat

```


## PCA

```{r pca, warning = F, message = F}
# Join the 2 mouse models in the same dataframes
pheno_ecx_J20['AD_model']='J20'
pheno_ecx_Tg4510['AD_model']='rTg4510'
pheno <- rbind(pheno_ecx_J20, pheno_ecx_Tg4510)

commonSites <- intersect(rownames(betas_ecx_J20), rownames(betas_ecx_Tg4510))
betas <- cbind(betas_ecx_J20[commonSites,], betas_ecx_Tg4510[commonSites,])

# order data
pheno <- pheno[order(rownames(pheno)),]
betas <- betas[,order(colnames(betas))]
print(identical(rownames(pheno), colnames(betas)))
```

```{r fig1, fig.cap = "Figure 1:  PCA plot highlighting the AD model"}
autoplot(prcomp(t(na.omit(betas))), data = pheno, colour = 'Genotype', shape = 'AD_model')
```

```{r fig2, fig.cap = "Figure 2:  PCA plot highlighting Age"}
autoplot(prcomp(t(na.omit(betas))), data = pheno, colour = 'Age_months', shape = 'Genotype')
```


### rTg4510

```{r pca rTg4510, warning = F, message = F}
print(identical(rownames(pheno_ecx_Tg4510), colnames(betas_ecx_Tg4510)))

autoplot(prcomp(t(na.omit(betas_ecx_Tg4510))), data = pheno_ecx_Tg4510, colour = 'Age_months', shape = 'Genotype')
```


### J20

```{r pca J20 , warning = F, message = F}
print(identical(rownames(pheno_ecx_J20), colnames(betas_ecx_J20)))

autoplot(prcomp(t(na.omit(betas_ecx_J20))), data = pheno_ecx_J20, colour = 'Age_months', shape = 'Genotype')
```

## Hierarchal clustering
### J20
```{r clusteringJ20, warning = F, message = F}

library(gplots)

sigmaJ20 <- apply(betas_ecx_J20, 1, sd) # to calculate the standard deviation of all probes
sigma <- sigmaJ20

plot(hclust(dist(t(betas_ecx_J20[order(sigma, decreasing = TRUE)[1:5000],]))), 
     labels = pheno_ecx_J20$Genotype, hang = -1 , cex = 0.68, main = "", xlab = "Genotype") 

plot(hclust(dist(t(betas_ecx_J20[order(sigma, decreasing = TRUE)[1:5000],]))), 
     labels = pheno_ecx_J20$Age_months, hang = -1 , cex = 0.68, main = "", xlab = "Age (months)")
```

### rTg4510
```{r clusteringTg4510, warning = F, message = F}

library(gplots)

sigmaTg4510 <- apply(betas_ecx_Tg4510, 1, sd) # to calculate the standard deviation of all probes
sigma <- sigmaTg4510

plot(hclust(dist(t(betas_ecx_Tg4510[order(sigma, decreasing = TRUE)[1:5000],]))), 
     labels = pheno_ecx_Tg4510$Genotype, hang = -1 , cex = 0.68, main = "", xlab = "Genotype") 

plot(hclust(dist(t(betas_ecx_Tg4510[order(sigma, decreasing = TRUE)[1:5000],]))), 
     labels = pheno_ecx_Tg4510$Age_months, hang = -1 , cex = 0.68, main = "", xlab = "Age (months)")
```

## Heatmaps

Heatmaps showing the top 1000 sites with the highest variance

```{r heatmaps, warning = F, message = F, fig.height=8}
# All ECX samples
metadata <- pheno[,c(1,2,5)]

library(pheatmap)
sigma <- apply(betas, 1, sd)
pheatmap(betas[order(sigma, decreasing = TRUE)[1:1000],],          
         annotation_col = metadata,
         cluster_rows = F,
         show_rownames = F,
         show_colnames = F, 
         main = "ECX")

# J20 ECX samples
metadata <- pheno_ecx_J20[,c(1,2)]

library(pheatmap)
sigma <- apply(betas_ecx_J20, 1, sd)

pheatmap(betas_ecx_J20[order(sigma, decreasing = TRUE)[1:1000],],          
         annotation_col = metadata,
         cluster_rows = F,
         show_rownames = F,
         show_colnames = F, 
         main = "J20")

# rTg4510 ECX samples
metadata <- pheno_ecx_Tg4510[,c(1,2)]

library(pheatmap)
sigma <- apply(betas_ecx_Tg4510, 1, sd)

pheatmap(betas_ecx_Tg4510[order(sigma, decreasing = TRUE)[1:1000],],          
         annotation_col = metadata,
         cluster_rows = F,
         show_rownames = F,
         show_colnames = F, 
         main = "rTg4510")


```

## Mouse Model Correlations

Checking if methylation is similar between similar biological groups. All levels will be compared, e.g AD model and genotype

```{r probe correlation, warning = F, message = F, fig.show = "hold", out.width = "50%"}
# pheno_ecx_J20
# betas_ecx_J20
# pheno_ecx_Tg4510
# betas_ecx_Tg4510


# Calculate average methylation for all individuals for each site
J20_probes <- apply(betas_ecx_J20[commonSites,], 1, mean)
Tg4510_probes <- apply(betas_ecx_Tg4510[commonSites,], 1, mean)

plot(J20_probes, Tg4510_probes, main = "J20 vs rTg4510")


############# J20 Genotype ##########
pheno_ecx_J20_WT <- pheno_ecx_J20[which(pheno_ecx_J20$Genotype %in% "WT"),]
betas_ecx_J20_WT <- betas_ecx_J20[, rownames(pheno_ecx_J20_WT)]

pheno_ecx_J20_TG <- pheno_ecx_J20[which(pheno_ecx_J20$Genotype %in% "TG"),]
betas_ecx_J20_TG <- betas_ecx_J20[, rownames(pheno_ecx_J20_TG)]

ECX_J20_WT <- apply(betas_ecx_J20_WT, 1, mean)
ECX_J20_TG <- apply(betas_ecx_J20_TG, 1, mean)

plot(ECX_J20_WT, ECX_J20_TG, main = "J20 WT vs TG")


############# Tg4510 Genotype ##########
pheno_ecx_Tg4510_WT <- pheno_ecx_Tg4510[which(pheno_ecx_Tg4510$Genotype %in% "WT"),]
betas_ecx_Tg4510_WT <- betas_ecx_Tg4510[, rownames(pheno_ecx_Tg4510_WT)]

pheno_ecx_Tg4510_TG <- pheno_ecx_Tg4510[which(pheno_ecx_Tg4510$Genotype %in% "TG"),]
betas_ecx_Tg4510_TG <- betas_ecx_Tg4510[, rownames(pheno_ecx_Tg4510_TG)]

ECX_Tg4510_WT <- apply(betas_ecx_Tg4510_WT, 1, mean)
ECX_Tg4510_TG <- apply(betas_ecx_Tg4510_TG, 1, mean)

plot(ECX_Tg4510_WT, ECX_Tg4510_TG, main = "rTg4510 WT vs TG")

```
